version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped

# Uncomment and configure if you need a database
# postgres:
#   image: postgres:15-alpine
#   container_name: postgres-db
#   environment:
#     POSTGRES_DB: nestjs_db
#     POSTGRES_USER: nestjs_user
#     POSTGRES_PASSWORD: nestjs_password
#   ports:
#     - "5432:5432"
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   networks:
#     - app-network

# Uncomment if you need Redis for caching/sessions
# redis:
#   image: redis:7-alpine
#   container_name: redis-cache
#   ports:
#     - "6379:6379"
#   networks:
#     - app-network

networks:
  app-network:
    driver: bridge

# Uncomment if using PostgreSQL
# volumes:
#   postgres_data: 